name: Add issue urgency

on:
  issues:
    types:
      - opened

jobs:
  add-issue-urgency:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue urgency
        uses: nipe0324/update-project-v2-item-field@v2.0.2
        with:
          project-url: https://github.com/users/GCHQ-Developer-847/projects/3
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          field-name: "Urgency"
          field-value: "High"
